#!/bin/bash

echo "📍 Apple Developer API 凭证输入位置指南"
echo "======================================"
echo
echo "🎯 在 MacSigner 应用中，您需要在以下位置输入凭证："
echo
echo "┌─────────────────────────────────────────┐"
echo "│           MacSigner 主界面               │"
echo "│                                         │"
echo "│  ┌─────────────┐  ┌─────────────┐      │"
echo "│  │  本地签名    │  │  设备管理    │ ← 点击这里"
echo "│  └─────────────┘  └─────────────┘      │"
echo "│                                         │"
echo "│  ┌─────────────┐  ┌─────────────┐      │"
echo "│  │  苹果凭证    │  │  服务器配置   │      │"
echo "│  └─────────────┘  └─────────────┘      │"
echo "└─────────────────────────────────────────┘"
echo
echo "👇 点击'设备管理'后，会看到："
echo
echo "┌─────────────────────────────────────────┐"
echo "│           设备管理界面                   │"
echo "│                                         │"
echo "│  ⚠️  Apple API 未配置                   │"
echo "│                                         │"
echo "│  ┌─────────────┐                       │"
echo "│  │  前往配置    │ ← 点击这里进入配置      │"
echo "│  └─────────────┘                       │"
echo "│                                         │"
echo "│  设备名称: [        ]                   │"
echo "│  设备UDID: [        ]                   │"
echo "│  平台: iOS ▼                           │"
echo "└─────────────────────────────────────────┘"
echo
echo "👇 点击'前往配置'后，会打开："
echo
echo "┌─────────────────────────────────────────┐"
echo "│        Apple API 配置窗口                │"
echo "│                                         │"
echo "│  Key ID:                               │"
echo "│  ┌─────────────────────────────────┐    │"
echo "│  │ 在这里输入您的10位Key ID         │ ← 这里！"
echo "│  └─────────────────────────────────┘    │"
echo "│                                         │"
echo "│  Issuer ID:                            │"
echo "│  ┌─────────────────────────────────┐    │"
echo "│  │ 在这里输入UUID格式Issuer ID      │ ← 这里！"
echo "│  └─────────────────────────────────┘    │"
echo "│                                         │"
echo "│  Private Key:                          │"
echo "│  ┌─────────────────────────────────┐    │"
echo "│  │ -----BEGIN PRIVATE KEY-----     │ ← 这里！"
echo "│  │ 粘贴完整的P8私钥文件内容         │"
echo "│  │ -----END PRIVATE KEY-----       │"
echo "│  └─────────────────────────────────┘    │"
echo "│                                         │"
echo "│  ┌─────────────┐  ┌─────────────┐      │"
echo "│  │  测试连接    │  │    保存      │      │"
echo "│  └─────────────┘  └─────────────┘      │"
echo "└─────────────────────────────────────────┘"
echo
echo "📝 填写示例："
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Key ID: ABC123DEFG"
echo "Issuer ID: 12345678-1234-1234-1234-123456789012"
echo "Private Key:"
echo "-----BEGIN PRIVATE KEY-----"
echo "MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQg..."
echo "-----END PRIVATE KEY-----"
echo
echo "🔍 如何获取这些信息："
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. 访问 App Store Connect (appstoreconnect.apple.com)"
echo "2. 进入'用户和访问权限' → '密钥'"
echo "3. 创建新的API密钥或查看现有密钥"
echo "4. Key ID 显示在密钥列表中"
echo "5. Issuer ID 显示在页面顶部"
echo "6. Private Key 需要下载.p8文件获取"
echo
echo "⚡ 快速测试方法（如果应用启动有问题）："
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "可以通过环境变量临时设置："
echo 'export APPLE_API_KEY_ID="您的Key ID"'
echo 'export APPLE_API_ISSUER_ID="您的Issuer ID"'
echo 'export APPLE_API_PRIVATE_KEY="完整私钥内容"'
echo
echo "然后运行: swift jwt_debug.swift"
echo
echo "🎯 您的目标位置：MacSigner → 设备管理 → 前往配置 → 填写表单"